# Generated by Django 3.2.5 on 2021-07-13 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('img_url', models.URLField()),
            ],
        ),
    ]
